### ISSUE TITLE
"Plugin Disabled"

### ISSUE THREAD

**Issue by McMelonTV** [JaxkDev/DiscordBot#9]
Fatal error: Uncaught AssertionError: Invalid message data received. in phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Utils.php:27
Stack trace:
#0 phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Bot/Handlers/PluginCommunicationHandler.php(57): JaxkDev\DiscordBot\Utils::assert(false, 'Invalid message...')
#1 phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Bot/Handlers/PluginCommunicationHandler.php(45): JaxkDev\DiscordBot\Bot\Handlers\PluginCommunicationHandler->handleSendMessage(Array)
#2 phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Bot/Client.php(171): JaxkDev\DiscordBot\Bot\Handlers\PluginCommunicationHandler->handle(Array)
#3 phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Bot/Client.php(143): JaxkDev\DiscordBot\Bot\Client->tick()
#4 phar:///home/container/plugins/DiscordBot_v1_0_0.phar/vendor/react/event-loop/src/Timer/Timers.php(96): JaxkDev\DiscordBot\Bot\Client->JaxkD in phar:///home/container/plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Utils.php on line 27

**Comment by McMelonTV** [comment]
@JaxkDev 
Could you help me please?

**Comment by JaxkDev** [comment]
Looking into it, If you have further info / logs please send over eg what message caused this ?
It wont be more then a second or two after the message was sent

**Comment by JaxkDev** [comment]
Actually its possible i got the ID constraints incorrect, can you paste your server ID and channel ID that you used in the config

**Comment by McMelonTV** [comment]
[2020-12-19T18:19:48.190784+00:00] DiscordPHP.HTTP.DEBUG: REQ GET https://discord.com/api/v6/gateway/bot queued [] []
[2020-12-19T18:19:48.196811+00:00] DiscordPHP.HTTP.WARNING: REQ GET https://discord.com/api/v6/gateway/bot failed: Connection to discord.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [] []
[2020-12-19T18:19:48.196859+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2020-12-19T18:19:48.196888+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2020-12-19T18:19:48.196914+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-12-19T18:19:48.252356+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to gateway.discord.gg:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"} []
[2020-12-19T18:35:20.591173+00:00] DiscordPHP.HTTP.DEBUG: REQ GET https://discord.com/api/v6/gateway/bot queued [] []
[2020-12-19T18:35:20.660242+00:00] DiscordPHP.HTTP.WARNING: REQ GET https://discord.com/api/v6/gateway/bot failed: Connection to discord.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [] []
[2020-12-19T18:35:20.660326+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2020-12-19T18:35:20.660369+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2020-12-19T18:35:20.660411+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-12-19T18:35:20.673158+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to gateway.discord.gg:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"} []
[2020-12-19T18:42:20.914782+00:00] DiscordPHP.HTTP.DEBUG: REQ GET https://discord.com/api/v6/gateway/bot queued [] []
[2020-12-19T18:42:20.970576+00:00] DiscordPHP.HTTP.WARNING: REQ GET https://discord.com/api/v6/gateway/bot failed: Connection to discord.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [] []
[2020-12-19T18:42:20.970697+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2020-12-19T18:42:20.970742+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2020-12-19T18:42:20.970793+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-12-19T18:42:21.026111+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to gateway.discord.gg:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"} []
[2020-12-19T18:44:46.225506+00:00] DiscordPHP.HTTP.DEBUG: REQ GET https://discord.com/api/v6/gateway/bot queued [] []
[2020-12-19T18:44:46.281427+00:00] DiscordPHP.HTTP.WARNING: REQ GET https://discord.com/api/v6/gateway/bot failed: Connection to discord.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [] []
[2020-12-19T18:44:46.281559+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2020-12-19T18:44:46.281607+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2020-12-19T18:44:46.281650+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-12-19T18:44:46.286111+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to gateway.discord.gg:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"} []





this is the log file

**Comment by McMelonTV** [comment]
and this is the events file:

---
version: 1

message:
  toDiscord:
    channels: [738135922884870224.789922140698181633]
    format: "[{TIME}] **{USERNAME}**: ```{MESSAGE}```"
  fromDiscord:
    channels: [738135922884870224.789922140698181633]
    format: "[{TIME}] {USERNAME}#{USER_DISCRIMINATOR} : {MESSAGE}"

command:
  toDiscord:
    channels: [738135922884870224.789922666844258356]
    format: "[{TIME}] **{USERNAME}** Used command: ```{COMMAND}```"

member_join:
  toDiscord:
    channels: [738135922884870224.789922140698181633]
    format: "[{TIME}] **{USERNAME}** Has joined KrypticParadise."
  fromDiscord:
    format: "[{TIME}] {USERNAME}#{USER_DISCRIMINATOR} Has joined KrypticParadise."

member_leave:
  toDiscord:
    channels: [738135922884870224.789922140698181633]
    format: "[{TIME}] **{USERNAME}** Has left KrypticParadise."
  fromDiscord:
    format: "[{TIME}] {USERNAME}#{USER_DISCRIMINATOR} Has left KrypticParadise."
...

**Comment by JaxkDev** [comment]
ok so for that massive error, see #8 thats an entire different thing.
For this issue you need to turn all the `channels: [123.123]` to `channels: ["123.123"]` but using your ID's instead of 123

**Comment by McMelonTV** [comment]
oh okay

**Comment by McMelonTV** [comment]
now this shows in the console:

[2020-12-19T19:04:52.039388+00:00] DiscordPHP.HTTP.DEBUG: REQ GET https://discord.com/api/v6/gateway/bot queued [] []
[2020-12-19T19:04:52.094948+00:00] DiscordPHP.HTTP.WARNING: REQ GET https://discord.com/api/v6/gateway/bot failed: Connection to discord.com:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [] []
[2020-12-19T19:04:52.095047+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2020-12-19T19:04:52.095094+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2020-12-19T19:04:52.095200+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-12-19T19:04:52.149678+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to gateway.discord.gg:443 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"} []

**Comment by McMelonTV** [comment]
and this



[19:05:22] [BotThread thread/CRITICAL]: Client failed to login/connect within 30 seconds, See log file for details.
[19:05:22] [Server thread/INFO]: Disabling DiscordBot v1.0.0

**Comment by JaxkDev** [comment]
> ok so for that massive error, see #8 thats an entire different thing.

**Comment by McMelonTV** [comment]
ah

**Comment by McMelonTV** [comment]
could you help me with that? also, i host the server on a hosting not on my local pc

**Comment by JaxkDev** [comment]
You got 4 options,
1. Beg @Weissnix4711 for the phar he built with disabled security.
2. Build it yourself ( see #8 )
3. Complain to your host about a cacert.pem
4. Configure your own cacert.pem if possible ( see #8 )

**Comment by McMelonTV** [comment]
oh
